name: "Terraform Destroy"

on:
  workflow_dispatch:

jobs:
  destroy:
    uses: freecloudinitiative/.github/.github/workflows/terraform-apply.yml@2816605944e9c3355e401d527f7f725b05b71ce5
    with:
      directory: '.'
    secrets: inherit
