name: "Terraform Destroy"

on:
  workflow_dispatch:

jobs:
  destroy:
    uses: freecloudinitiative/.github/.github/workflows/terraform-apply.yml@main
    with:
      directory: '.'
    secrets: inherit
