name: "Terraform Apply"

on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
  workflow_dispatch:

jobs:
  apply:
    uses: freecloudinitiative/.github/.github/workflows/terraform-apply.yml@main
    with:
      directory: '.'
    secrets: inherit
