name: "Terraform PR Check"

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: freecloudinitiative/.github/.github/workflows/terraform-pr-checker.yml@2816605944e9c3355e401d527f7f725b05b71ce5
    with:
      directories: '["gcp", "azure", "aws", "linode"]'
      plan: false
    secrets: inherit
